name: CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          # apt install -y bash coreutils libc-bin libc6:amd64 libpython3.12-minimal:amd64 libpython3.12-stdlib:amd64 locales ncurses-base python3.12-minimal tzdata
          python -m pip install --upgrade --disable-pip-version-check pip
          pip install . pytest pytest-cov
      - name: Run tests
        run: pytest
